# fly.toml app configuration file generated for portugiesisch-lern-pwa on 2026-10-04T14:22:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "portugiesisch-lern-pwa"
primary_region = "fra"

[build]
  builder = "docker"

[env]
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "15s"
    method = "GET"
    path = "/"
    timeout = "2s"
